{
 "title": "Active Connections",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "query0",
    "query": {
     "query": "label_values(pg_database_size_bytes,datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temp Files Created (per sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_temp_files{job=\"postgresql\", instance=\"my_postgresql_db\", datname=\"$query0\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size (GB)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"$query0\"} / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocks Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_database_deadlocks{datname=\"$query0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollbacks Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"$query0\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Processing Speed (QPS)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"$query0\"}[5m]) + (rate(pg_stat_database_xact_rollback{datname=\"$query0\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Metrics (System Monitoring)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Operations Rate",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=\"$query0\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=\"techno musin events\"}[5m]) / (rate(pg_stat_database_blks_hit{datname=\"techno musin events\"}[5m]) + rate(pg_stat_database_blks_read{datname=\"techno musin events\"}[5m]))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=\"$query0\"}[5m]) / (rate(pg_stat_database_blks_hit{datname=\"$query0\"}[5m]) + (rate(pg_stat_database_blks_read{datname=\"techno musin events\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Operations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read{datname=\"$query0\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Per Second (TPS)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"$query0\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=~\"$query0\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}